### ISSUE TITLE
floating joint

### ISSUE THREAD

**Issue by MariaBana** [jstmn/Jrl#7]
Hello!
Thank you for such a great work, this is very useful for solving robotics problems quickly!

I checked your repository and saw that floating joints are not currently supported. I was wondering if you have any plans to support floating joints? This is crucial for mobile robots and is urgently needed for my current research too.

**Comment by jstmn** [comment]
Hi, glad to hear you're finding it useful! 

Floating joints shouldn't be an issue, I'll take a crack at implementing this joint type this week. 

Also, what robot are you using?

**Comment by jstmn** [comment]
Hey, can you clarify what exactly you want the FK function to do for the aliengo? Do you want it to return the pose of each of the 4 feet?

This code is designed for single chain kinematic systems, so only a single end effector is possible

**Comment by jstmn** [comment]
Hey, this would require a non trivial amount of work to implement so unfortunately I don't think i'm going to do it. The issue is that the current FK and jacobian code is written with the assumption that each joint has 1 dof, but floating joints have 6dof. 

A straightforward workaround (afaik) would be to add three prismatic joints, and three revolute joints for the positional and rotational component of the base of the robot. Any reason that shouldn't work?
